name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-8-jdk \
            git-core gnupg flex bison gperf build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
            xsltproc unzip fontconfig

      - name: Checkout AOSP manifest
        run: |
          mkdir ~/bin || true
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir aosp10
          cd aosp10
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Sync required projects
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          repo sync -c -j$(nproc) \
            build/make \
            build/soong \
            build/blueprint \
            system/core \
            system/libhidl \
            system/tools/hidl \
            external/libcxx \
            external/gtest \
            prebuilts/clang/host/linux-x86 \
            prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 \
            prebuilts/go/linux-x86

      - name: Build hidl-gen
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          source build/envsetup.sh
          lunch aosp_arm-eng
          m hidl-gen -j$(nproc)

      - name: Upload hidl-gen binary
        uses: actions/upload-artifact@v4
        with:
          name: hidl-gen
          path: aosp10/out/host/linux-x86/bin/hidl-gen
