jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y clang llvm libbpf-dev linux-headers-generic linux-libc-dev build-essential

      - name: Prepare kernel headers
        run: |
          sudo make -C /usr/src/linux-headers-$(uname -r) headers_install INSTALL_HDR_PATH=/tmp/kernel-headers

      - name: Build
        run: |
          clang -O2 -g -target bpf \
            -I/tmp/kernel-headers/include \
            -c hi.c -o hi.o

      - uses: actions/upload-artifact@v4
        with:
          name: hi.o
          path: hi.o
