name: Build Android 10 Overlay

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup NDK
      run: |
        export NDK=$HOME/ndk
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -O ndk.zip
        unzip -q ndk.zip -d $HOME
        mv $HOME/android-ndk-r27c $NDK
        echo "NDK=$NDK" >> $GITHUB_ENV

    - name: Setup Android 10 headers
      run: |
        mkdir -p $HOME/aosp_headers
        cd $HOME/aosp_headers
        # Clone Android 10 frameworks/native (API 29)
        git clone https://android.googlesource.com/platform/frameworks/native -b android-10.0.0_r47
        mkdir -p native/include/android/gui
        # Fake missing header
        cat > native/include/android/gui/FrameTimelineInfo.h <<EOF
        #pragma once
        namespace android {
        namespace gui {
            struct FrameTimelineInfo {
                int64_t vsyncId = 0;
                int64_t inputEventId = 0;
                int64_t presentTime = 0;
            };
        }}
        EOF
        echo "AOSP_HEADERS=$HOME/aosp_headers" >> $GITHUB_ENV

    - name: Build overlay
      run: |
        $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -I$AOSP_HEADERS/native/include \
          -shared -fPIC overlay.cpp -o overlay.so

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: overlay-android10
        path: overlay.so
