name: Build Overlay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip -q android-ndk-r27c-linux.zip -d $PWD
          mv android-ndk-r27c ndk
          echo "NDK=$PWD/ndk" >> $GITHUB_ENV

      - name: Clone AOSP headers
        run: |
          mkdir -p aosp_headers
          git clone --depth=1 https://android.googlesource.com/platform/frameworks/native aosp_headers/native
          git clone --depth=1 https://android.googlesource.com/platform/frameworks/av aosp_headers/av
          git clone --depth=1 https://android.googlesource.com/platform/frameworks/base aosp_headers/base

          # Copy missing headers if needed
          find aosp_headers/base -name "com_android_graphics_libgui_flags.h" -exec cp {} aosp_headers/native/include/ \; || true
          find aosp_headers/native -name "FrameTimelineInfo.h" -exec cp {} aosp_headers/native/include/android/gui/ \; || true

      - name: Build overlay.cpp
        run: |
          $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
            -I./aosp_headers/native/include \
            -I./aosp_headers/av/include \
            -I./aosp_headers/base/core/java \
            -std=c++17 \
            -fPIC -shared overlay.cpp -o liboverlay.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: overlay-lib
          path: liboverlay.so
