name: Android Overlay Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and Unzip Android NDK
      run: |
        # URL của Android NDK r21d
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip"
        NDK_DIR="android-ndk-r21d"

        echo "Downloading Android NDK from $NDK_URL..."
        wget -q $NDK_URL
        
        echo "Unzipping the NDK package..."
        unzip -q android-ndk-r21d-linux-x86_64.zip
        
        # Thiết lập biến môi trường
        echo "ANDROID_NDK_HOME=$PWD/$NDK_DIR" >> $GITHUB_ENV
        echo "$PWD/$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        
        echo "Android NDK setup complete."

    - name: Build with Android NDK
      run: |
        # Đảm bảo các biến môi trường đã được thiết lập
        if [ -z "$ANDROID_NDK_HOME" ]; then
          echo "Error: ANDROID_NDK_HOME is not set."
          exit 1
        fi
        
        # Tên tệp đầu ra của bạn
        APP_NAME=overlayApp
        
        # Gọi trình biên dịch clang++
        echo "Building the overlay application..."
        clang++ overlay.cpp -o $APP_NAME -fpermissive -landroid -lEGL -lGLESv2 -lgnustl_shared
        
        echo "Build complete."

    - name: Upload built application as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: OverlayApp
        retention-days: 7
        
