name: Android Overlay Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip -q android-ndk-r27c-linux.zip
        mv android-ndk-r27c $HOME/ndk

    - name: Clone AOSP headers
      run: |
        mkdir -p $HOME/aosp_headers
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/native $HOME/aosp_headers/native
        git clone --depth=1 https://android.googlesource.com/platform/system/core $HOME/aosp_headers/system_core

    - name: Build overlay.so
      run: |
        $HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ \
          --target=aarch64-linux-android29 \
          -D__ANDROID_API__=29 \
          -std=c++17 -fPIC -shared \
          -I$HOME/aosp_headers/native/include \
          -I$HOME/aosp_headers/native/libs/ui/include \
          -I$HOME/aosp_headers/native/libs/gui/include \
          -I$HOME/aosp_headers/system_core/base/include \
          overlay.cpp -o overlay.so

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: overlay-lib
        path: overlay.so
