name: Build eBPF

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y clang llvm libbpf-dev linux-libc-dev build-essential

      - name: Build
        run: |
          clang -O2 -g -target bpf -c hi.c -o hi.o

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hi.o
          path: hi.o
