name: Android NDK Build with Extended AOSP headers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip -q android-ndk-r27c-linux.zip
        mv android-ndk-r27c ndk

    - name: Download AOSP headers
      run: |
        mkdir aosp_headers
        cd aosp_headers
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/native
        git clone --depth=1 https://android.googlesource.com/platform/system/core
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/base
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/av

    - name: Build with NDK + AOSP headers
      run: |
        export NDK=$PWD/ndk
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export API=21
        export ARCH=aarch64
        $TOOLCHAIN/bin/${ARCH}-linux-android${API}-clang++ \
          -shared -fPIC overlay.cpp -o liboverlay.so \
          -I$PWD/aosp_headers/native/include \
          -I$PWD/aosp_headers/native/aidl/gui/include \
          -I$PWD/aosp_headers/core/libutils/include \
          -I$PWD/aosp_headers/base/include \
          -I$PWD/aosp_headers/av/include \
          -I$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: liboverlay
        path: liboverlay.so
