name: Build Overlay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip -q android-ndk-r27c-linux.zip
        mv android-ndk-r27c ndk

    - name: Setup AOSP headers
      run: |
        mkdir -p aosp_headers
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/native aosp_headers/native || true
        git clone --depth=1 https://android.googlesource.com/platform/frameworks/base aosp_headers/aidl || true

    - name: Mock FrameTimelineInfo.h
      run: |
        mkdir -p aosp_headers/native/include/android/gui
        cat > aosp_headers/native/include/android/gui/FrameTimelineInfo.h <<'EOF'
        #pragma once
        #include <stdint.h>
        namespace android::gui {
        struct FrameTimelineInfo {
            int64_t vsyncId = 0;
            int64_t inputEventId = 0;
        };
        }
        EOF

    - name: Build overlay
      run: |
        export NDK=$PWD/ndk
        $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -I aosp_headers/native/include \
          -I aosp_headers/aidl/include \
          -std=c++17 -shared -fPIC overlay.cpp -o liboverlay.so

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: liboverlay
        path: liboverlay.so
