name: Build hidl-gen (Android 10)

on:
  workflow_dispatch:   # cho phép trigger thủ công

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk git-core gnupg flex bison gperf \
            build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Init AOSP repo (Android 10)
        run: |
          mkdir aosp && cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r1
          repo sync -c -j4

      - name: Build hidl-gen
        run: |
          cd aosp
          source build/envsetup.sh
          lunch aosp_arm-eng
          m hidl-gen

      - name: Generate headers for android.hardware.graphics.common@1.1
        run: |
          cd aosp
          out/host/linux-x86/bin/hidl-gen -L c++-headers \
            -r android.hardware:hardware/interfaces \
            -r android.hidl:system/libhidl/transport \
            android.hardware.graphics.common@1.1
          mkdir -p $GITHUB_WORKSPACE/gen_headers
          find out -type f -path "*/gen/*" -name "*.h" -exec cp --parents {} $GITHUB_WORKSPACE/gen_headers \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hidl-headers
          path: gen_headers
