name: Build eBPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang llvm libelf-dev gcc-multilib build-essential linux-headers-$(uname -r)

      - name: Build eBPF program
        run: |
          clang -O2 -target bpf -c hi.c -o hi.o
