name: Build Overlay for Android 10

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Android NDK
      run: |
        mkdir -p $HOME/ndk
        curl -sSL https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -o ndk.zip
        unzip -q ndk.zip -d $HOME
        mv $HOME/android-ndk-r27c $HOME/ndk

    - name: Clone AOSP headers (Android 10)
      run: |
        mkdir -p $HOME/aosp_headers
        git clone --depth=1 -b android-10.0.0_r41 https://android.googlesource.com/platform/frameworks/native $HOME/aosp_headers/native
        git clone --depth=1 -b android-10.0.0_r41 https://android.googlesource.com/platform/system/core $HOME/aosp_headers/system_core

    - name: Build overlay.so
      run: |
        $HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -std=c++17 -fPIC -shared \
          -I$HOME/aosp_headers/native/include \
          -I$HOME/aosp_headers/native/libs/ui/include \
          -I$HOME/aosp_headers/system_core/base/include \
          overlay.cpp -o overlay.so

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: overlay-android10
        path: overlay.so
