name: Build Android NDK Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip -O ndk.zip
        unzip ndk.zip -d $GITHUB_WORKSPACE/ndk
        echo "NDK_PATH=$GITHUB_WORKSPACE/ndk/android-ndk-r21" >> $GITHUB_ENV

    - name: Build with NDK
      run: |
        export ANDROID_NDK_HOME=${{ env.NDK_PATH }}
        $ANDROID_NDK_HOME/ndk-build  # Removed cd myoverlay if files are in root

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: myoverlay-build
        path: libs/**  # Adjusted path since files are likely in root
