name: Android Overlay Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android-ndk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Android NDK
      uses: android-ndk-r21-setup@v1  # Sử dụng action khác
      with:
        ndk-version: '21.4.7075529'   # Phiên bản NDK của bạn

    - name: Build with Android NDK
      run: |
        export NDK_ROOT=$ANDROID_NDK_HOME
        export PATH=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

        APP_NAME=OverlayApp

        clang++ Overlay.cpp -o $APP_NAME -fpermissive -landroid -lEGL -lGLESv2 -lgnustl_shared

    - name: List built files
      run: ls -l
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: OverlayApp
        
