name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04   # AOSP 10 yêu cầu 20.04 ổn định hơn
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cài dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Cài repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Config git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Init AOSP 10 manifest
      run: |
        mkdir aosp10 && cd aosp10
        repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

    - name: Sync tối thiểu cho hidl-gen
      run: |
        cd aosp10
        repo sync -c -j$(nproc) \
          build/make \
          build/soong \
          build/blueprint \
          system/tools/hidl \
          system/libhidl \
          system/core/base \
          system/core/liblog \
          external/libcxx \
          external/gtest \
          external/googletest \
          external/protobuf \
          prebuilts/clang/host/linux-x86 \
          prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 \
          prebuilts/go/linux-x86 \
          prebuilts/sdk \
          prebuilts/vndk/v29

    - name: Build hidl-gen
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng
        m hidl-gen -j$(nproc)

    - name: Upload hidl-gen
      uses: actions/upload-artifact@v4
      with:
        name: hidl-gen
        path: out/host/linux-x86/bin/hidl-gen
