- name: Install hidl-gen (from Debian package)
        run: |
          sudo apt-get update
          sudo apt-get install -y android-platform-system-tools-hidl
          mkdir -p aosp10/out/host/linux-x86/bin
          cp $(which hidl-gen) aosp10/out/host/linux-x86/bin/hidl-gen

      - name: Upload hidl-gen binary
        uses: actions/upload-artifact@v4
        with:
          name: hidl-gen
          path: aosp10/out/host/linux-x86/bin/hidl-gen
