name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig golang

      - name: Download repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Init AOSP 10 repo
        run: |
          export PATH=~/bin:$PATH
          mkdir -p aosp10 && cd aosp10
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Sync required projects
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          repo sync -c -j$(nproc) \
            build/soong \
            build/blueprint \
            system/core/liblog \
            system/libhidl \
            system/tools/hidl \
            external/libcxx

      - name: Patch microfactory to use system Go
        run: |
          cd aosp10
          # Blueprint microfactory
          sed -i 's|.*/prebuilts/go/linux-x86.*/bin/go|go|g' build/blueprint/microfactory/microfactory.bash || true
          sed -i 's|cd .*prebuilts/go/linux-x86.*||g' build/blueprint/microfactory/microfactory.bash || true

          # Soong microfactory
          sed -i 's|.*/prebuilts/go/linux-x86.*/bin/go|go|g' build/soong/scripts/microfactory.bash || true
          sed -i 's|cd .*prebuilts/go/linux-x86.*||g' build/soong/scripts/microfactory.bash || true

          echo ">>> Blueprint script:"
          grep -n "go" build/blueprint/microfactory/microfactory.bash || true
          echo ">>> Soong script:"
          grep -n "go" build/soong/scripts/microfactory.bash || true

      - name: Build hidl-gen
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          source build/envsetup.sh || true
          lunch aosp_arm-eng || true
          ALLOW_MISSING_DEPENDENCIES=true m hidl-gen

      - name: Upload hidl-gen binary
        uses: actions/upload-artifact@v4
        with:
          name: hidl-gen
          path: aosp10/out/host/linux-x86/bin/hidl-gen
