name: Build hidl-gen (Android 10)

on:
  workflow_dispatch:   # chạy thủ công
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04   # hoặc 20.04 cho ổn định

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cài đặt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Thiết lập repo tool
      run: |
        mkdir -p ~/bin
        export PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Lấy source Android 10.0.0_r47
      run: |
        mkdir aosp10 && cd aosp10
        ~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47
        ~/bin/repo sync -c -j$(nproc)

    - name: Thiết lập môi trường build
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng

    - name: Build hidl-gen
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng
        m hidl-gen

    - name: Upload hidl-gen binary
      uses: actions/upload-artifact@v4
      with:
        name: hidl-gen
        path: aosp10/out/host/linux-x86/bin/hidl-gen
