name: Build AOSP with Google Drive + ccache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps + rclone + ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone fuse ccache

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Mount Google Drive
        run: |
          mkdir -p ~/gdrive
          nohup rclone mount gdrive:/aosp ~/gdrive --daemon --vfs-cache-mode writes &
          sleep 10

      - name: Check disk space
        run: df -h ~/gdrive

      - name: Sync source to Google Drive
        run: |
          rsync -av --progress ./ ~/gdrive/source

      - name: Enable ccache
        run: |
          export USE_CCACHE=1
          export CCACHE_DIR=~/gdrive/ccache
          ccache -M 50G
          ccache -z

      - name: Build AOSP
        run: |
          cd ~/gdrive/source
          export USE_CCACHE=1
          export CCACHE_DIR=~/gdrive/ccache
          source build/envsetup.sh
          lunch aosp_arm-eng
          make -j$(nproc)

      - name: Save ccache stats
        run: |
          ccache -s

      - name: Upload output (optional)
        run: |
          mkdir -p ~/artifacts
          cp -r ~/gdrive/source/out/target/product/* ~/artifacts/ || true
          echo "Artifacts saved in ~/artifacts"
