name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Setup Go 1.12.17 (required for AOSP 10 soong)
        uses: actions/setup-go@v5
        with:
          go-version: '1.12.17'

      - name: Download repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Init AOSP 10 repo (minimal)
        run: |
          export PATH=~/bin:$PATH
          mkdir -p aosp10 && cd aosp10
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Sync required projects (minimal, clean)
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          repo sync -c -j$(nproc) \
            build/make \
            build/soong \
            build/blueprint \
            prebuilts/build-tools \
            prebuilts/misc \
            prebuilts/sdk \
            system/core \
            system/tools/hidl \
            system/libhidl \
            external/libcxx \
            external/libchrome \
            external/expat \
            external/golang-protobuf \
            external/protobuf \
            external/googletest

      - name: Fetch VNDK v28 (fix missing prebuilts)
        run: |
          cd aosp10
          git clone https://android.googlesource.com/platform/prebuilts/vndk/v28 prebuilts/vndk/v28
          cd prebuilts/vndk/v28
          git checkout android-10.0.0_r47

      - name: Force Go 1.12.17 into prebuilts/go
        run: |
          cd aosp10
          rm -rf prebuilts/go
          mkdir -p prebuilts/go/linux-x86
          GOROOT=$(go env GOROOT)
          echo "Using Go from $GOROOT"
          cp -a $GOROOT/* prebuilts/go/linux-x86/
          ls -l prebuilts/go/linux-x86/bin/go
          prebuilts/go/linux-x86/bin/go version

      - name: Build hidl-gen only (skip lunch)
        run: |
          export PATH=~/bin:$PATH
          cd aosp10
          export ALLOW_MISSING_DEPENDENCIES=true
          export SOONG_ALLOW_MISSING_DEPENDENCIES=true
          export WITHOUT_CHECK_API=true
          build/soong/soong_ui.bash --make-mode hidl-gen

      - name: Upload hidl-gen binary
        uses: actions/upload-artifact@v4
        with:
          name: hidl-gen
          path: aosp10/out/host/linux-x86/bin/hidl-gen
