name: Build hidl-gen (Slim)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Cài dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Clone repos cần thiết
      run: |
        mkdir aosp10 && cd aosp10
        git clone https://android.googlesource.com/platform/build build -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/build/soong build/soong -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/system/tools/hidl system/tools/hidl -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/system/libbase system/libbase -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/system/libhidl system/libhidl -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/system/libfmq system/libfmq -b android-10.0.0_r47
        git clone https://android.googlesource.com/platform/system/core system/core -b android-10.0.0_r47

    - name: Build hidl-gen
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng
        m hidl-gen

    - name: Upload hidl-gen binary
      uses: actions/upload-artifact@v4
      with:
        name: hidl-gen
        path: aosp10/out/host/linux-x86/bin/hidl-gen
