name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04   # bản Ubuntu ổn định cho AOSP 10

    steps:
    - name: Checkout (empty)
      uses: actions/checkout@v4

    - name: Cài dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
          zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
          x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
          xsltproc unzip fontconfig python3 rsync

    - name: Setup repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Init AOSP 10 manifest
      run: |
        mkdir aosp10 && cd aosp10
        repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

    - name: Repo sync với timeout + keepalive
      run: |
        cd aosp10
        # keepalive background
        (while true; do echo "⏳ Syncing... $(date)"; sleep 60; done) &
        # timeout để tránh treo
        timeout 25m repo sync -c -j$(nproc) || echo "⚠️ repo sync failed or timeout"

    - name: Build hidl-gen
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng
        # chỉ build hidl-gen
        m hidl-gen 2>&1 | tee $GITHUB_WORKSPACE/hidl-gen.log
