name: Build hidl-gen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo manifest
        run: |
          mkdir aosp10
          cd aosp10
          git clone https://android.googlesource.com/platform/manifest .repo/manifests
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Download required AOSP repos
        run: |
          cd aosp10
          repo sync -c -j$(nproc) \
            build/make \
            build/soong \
            build/blueprint \
            system/core \
            system/libhidl \
            system/tools/hidl \
            external/libcxx \
            external/gtest \
            prebuilts/clang/host/linux-x86 \
            prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8 \
            prebuilts/go/linux-x86

      - name: Setup environment
        run: |
          cd aosp10
          export PATH=~/bin:$PATH
          source build/envsetup.sh

      - name: Build hidl-gen
        run: |
          cd aosp10
          source build/envsetup.sh
          m hidl-gen -j$(nproc)

      - name: Upload hidl-gen binary
        uses: actions/upload-artifact@v4
        with:
          name: hidl-gen
          path: aosp10/out/host/linux-x86/bin/hidl-gen
