name: Build hidl-gen (Android 10 r47, VNDK Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Setup repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Init AOSP manifest (android-10.0.0_r47)
      run: |
        mkdir aosp10 && cd aosp10
        repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

    - name: Partial repo sync (deps for hidl-gen + VNDK)
      run: |
        cd aosp10
        repo sync -c -j$(nproc) \
          build/make \
          build/blueprint \
          build/kati \
          build/soong \
          system/core \
          system/libhidl \
          system/libfmq \
          system/tools/hidl \
          prebuilts/go/linux-x86 \
          prebuilts/clang/host/linux-x86 \
          prebuilts/misc \
          prebuilts/sdk \
          prebuilts/build-tools \
          prebuilts/devtools \
          prebuilts/vndk/v28 \
          prebuilts/vndk/v29 \
          external/golang-protobuf \
          external/protobuf \
          external/googletest \
          external/gflags \
          external/jemalloc \
          external/boringssl \
          external/zlib \
          external/libcxx

    - name: Setup build environment
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng

    - name: Build hidl-gen
      run: |
        cd aosp10
        source build/envsetup.sh
        lunch aosp_arm-eng
        m hidl-gen

    - name: Upload hidl-gen binary
      uses: actions/upload-artifact@v4
      with:
        name: hidl-gen
        path: aosp10/out/host/linux-x86/bin/hidl-gen
